name: Run Discord Bot Twice Daily

on:
  schedule:
    - cron: '0 23 * * *'   # 00:00 lokal
    - cron: '0 11 * * *'   # 12:00 lokal
    - cron: '0 19 * * *'   # 20:00 lokal
  workflow_dispatch:


jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        run: python main.py
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
