name: Tick Check 6min (05:50–10:44 UTC)

on:
  schedule:
    - cron: '50 5 * * *'
    - cron: '56 5 * * *'
    - cron: '2 6 * * *'
    - cron: '8 6 * * *'
    - cron: '14 6 * * *'
    - cron: '20 6 * * *'
    - cron: '26 6 * * *'
    - cron: '32 6 * * *'
    - cron: '38 6 * * *'
    - cron: '44 6 * * *'
    - cron: '50 6 * * *'
    - cron: '56 6 * * *'
    - cron: '2 7 * * *'
    - cron: '8 7 * * *'
    - cron: '14 7 * * *'
    - cron: '20 7 * * *'
    - cron: '26 7 * * *'
    - cron: '32 7 * * *'
    - cron: '38 7 * * *'
    - cron: '44 7 * * *'
    - cron: '50 7 * * *'
    - cron: '56 7 * * *'
    - cron: '2 8 * * *'
    - cron: '8 8 * * *'
    - cron: '14 8 * * *'
    - cron: '20 8 * * *'
    - cron: '26 8 * * *'
    - cron: '32 8 * * *'
    - cron: '38 8 * * *'
    - cron: '44 8 * * *'
    - cron: '50 8 * * *'
    - cron: '56 8 * * *'
    - cron: '2 9 * * *'
    - cron: '8 9 * * *'
    - cron: '14 9 * * *'
    - cron: '20 9 * * *'
    - cron: '26 9 * * *'
    - cron: '32 9 * * *'
    - cron: '38 9 * * *'
    - cron: '44 9 * * *'
    - cron: '50 9 * * *'
    - cron: '56 9 * * *'
    - cron: '2 10 * * *'
    - cron: '8 10 * * *'
    - cron: '14 10 * * *'
    - cron: '20 10 * * *'
    - cron: '26 10 * * *'
    - cron: '32 10 * * *'
    - cron: '38 10 * * *'
    - cron: '44 10 * * *'

  workflow_dispatch:

jobs:
  tick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore tick cache
        uses: actions/cache@v3
        with:
          path: tick_cache
          key: tick-cache-${{ github.run_id }}
          restore-keys: |
            tick-cache-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tick Check
        run: python tick_check.py
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

      - name: Save updated tick cache
        uses: actions/cache/save@v3
        with:
          path: tick_cache
          key: tick-cache-${{ github.run_id }}
