name: Tick Check (No Cache Needed)

on:
  schedule:
  - cron: '30 6 * * *'
  - cron: '36 6 * * *'
  - cron: '42 6 * * *'
  - cron: '48 6 * * *'
  - cron: '54 6 * * *'
  - cron: '0 7 * * *'
  - cron: '6 7 * * *'
  - cron: '12 7 * * *'
  - cron: '18 7 * * *'
  - cron: '24 7 * * *'
  - cron: '30 7 * * *'
  - cron: '36 7 * * *'
  - cron: '42 7 * * *'
  - cron: '48 7 * * *'
  - cron: '54 7 * * *'
  - cron: '0 8 * * *'
  - cron: '6 8 * * *'
  - cron: '12 8 * * *'
  - cron: '18 8 * * *'
  - cron: '24 8 * * *'
  - cron: '30 8 * * *'
  - cron: '36 8 * * *'
  - cron: '42 8 * * *'
  - cron: '48 8 * * *'
  - cron: '54 8 * * *'
  - cron: '0 9 * * *'
  - cron: '6 9 * * *'
  - cron: '12 9 * * *'
  - cron: '18 9 * * *'
  - cron: '24 9 * * *'
  - cron: '30 9 * * *'
  - cron: '36 9 * * *'
  - cron: '42 9 * * *'
  - cron: '48 9 * * *'
  - cron: '54 9 * * *'
  - cron: '0 10 * * *'
  - cron: '6 10 * * *'
  - cron: '12 10 * * *'
  - cron: '18 10 * * *'
  - cron: '24 10 * * *'
  - cron: '30 10 * * *'
  - cron: '36 10 * * *'
  - cron: '42 10 * * *'
  - cron: '48 10 * * *'
  - cron: '54 10 * * *'
  workflow_dispatch:

jobs:
  tick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tick Check
        run: python tick_check.py
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
